version: '3.3'

services:
  db:
    container_name: 'banner_postgres'
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./scripts/structer.sql:/docker-entrypoint-initdb.d/structer.sql

  server:
    container_name: 'banner_service'
    build: ./
    command: ./avito-app
    image: 'banner'
    depends_on:
      - db
      - cache
    ports:
      - '8000:8000'

  cache:
    restart: always
    image: redis:7.2.4-bookworm
    ports:
      - 6379:6379